// lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // =========================
  // ANDROID
  // =========================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX-hG_91x3-zixv_HtfhhOj8ePT49WQPk',
    appId: '1:1055192434275:android:2715f36f40f719fba0da56',
    messagingSenderId: '1055192434275',
    projectId: 'leave-management-system-2fd8d',

    // FIXED
    storageBucket: 'leave-management-system-2fd8d.appspot.com',
  );

  // =========================
  // WEB
  // =========================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbpuEwM_x_sTh41QrERN1Q5uoKlhZWCpo',
    appId: '1:1055192434275:web:97a5b89811798089a0da56',
    messagingSenderId: '1055192434275',
    projectId: 'leave-management-system-2fd8d',
    authDomain: 'leave-management-system-2fd8d.firebaseapp.com',

    // FIXED
    storageBucket: 'leave-management-system-2fd8d.appspot.com',

    measurementId: 'G-V7NXJ1DR2Y',
  );

  // =========================
  // MACOS
  // =========================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVyRgjd2ikhjJA0ZTwFI-016jnwZaqZA',
    appId: '1:1055192434275:ios:e8c94e7e57658a26a0da56',
    messagingSenderId: '1055192434275',
    projectId: 'leave-management-system-2fd8d',

    // FIXED
    storageBucket: 'leave-management-system-2fd8d.appspot.com',

    iosBundleId: 'com.example.wil',
  );

  // =========================
  // IOS
  // =========================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVyRgjd2ikhjJA0ZTwFI-016jnwZaqZA',
    appId: '1:1055192434275:ios:e8c94e7e57658a26a0da56',
    messagingSenderId: '1055192434275',
    projectId: 'leave-management-system-2fd8d',

    // FIXED
    storageBucket: 'leave-management-system-2fd8d.appspot.com',

    iosBundleId: 'com.example.wil',
  );

  // =========================
  // WINDOWS
  // =========================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbpuEwM_x_sTh41QrERN1Q5uoKlhZWCpo',
    appId: '1:1055192434275:web:f42566ab7eb2ca3fa0da56',
    messagingSenderId: '1055192434275',
    projectId: 'leave-management-system-2fd8d',
    authDomain: 'leave-management-system-2fd8d.firebaseapp.com',

    // FIXED
    storageBucket: 'leave-management-system-2fd8d.appspot.com',

    measurementId: 'G-1MFCEH4E0G',
  );
}